### ISSUE TITLE
BUG:  label names

### ISSUE THREAD

**Issue by keoflex** [thewizster/workorders#11]
When two labels have the same name they don't submit all the data.  I did not think this would be a problem at first but found it is.  For instance on our budget  request form we have 

From Account
Amount

From Account
Amount

From Account 
Amount

To Account
Amount
________________________________-

Work around for this is 
1. From Account
1. Amount

2. From Account ... etc

Not a major problem, but I think some of the other admins will run into this even if we tell them it can not be the same name

**Comment by thewizster** [comment]
I believe this is a view/rendering issue only but I will verify and fix.

**Comment by thewizster** [comment]
This is fixed and will be included in the next commit on the develop branch.
