### ISSUE TITLE
FEATURE: Collaboration 

### ISSUE THREAD

**Issue by keoflex** [thewizster/workorders#3]
Build a system where approves can add a collaborator.

- We could do this by email or from a list of people in a group

- Once the collaborator has marked it  as Return (Unresolved), Return (resolved) along with notes of what they did or had trouble with, then it will go back to the person asking  for  help for approval or final approval
-Might even want the ability for collaborators to add more collaborators however I think that once it is approved and goes to the next  tear it would close any ability for collaborators to work on the work order.  This way its tier-based

Just ideas though

**Comment by thewizster** [comment]
Still working on the collab feature. Just need some feedback on a few things.

At this point I am setting a field in the user table called collaborator. If a user record has this field set to 1 the user will appear in the list of collabs to choose from. This way we can limit collaborators to registered users. Would you prefer another method for flagging collabs?

Also, will the collab need to be able to view/comment from the link they receive without having to log in?

**Comment by thewizster** [comment]
Just a quick update on the status here. Most of the work on this feature is completed. Hope to have it available for testing on the develop branch within the next week.

**Comment by keoflex** [comment]
Awsome!
