### ISSUE TITLE
BUG: form and approvers wiped out

### ISSUE THREAD

**Issue by keoflex** [thewizster/workorders#5]
I was building a form and then adding users and the system erased all content and users.

Possible cause
1.  I added html tags `<center><strong>some text here</strong></center>` to one of the titles 

2.  I manually refreshed the page (didn't realize it didn't load the data back in and then clicked save)

Before the issue was happening the save button was broke.  It would not saved the workorder which is why I refreshed the page and clicked save.

Created a new workorder and did everything the same except the HTML tags and it seems to be fine

**Comment by thewizster** [comment]
Where you adding HTML to a form builder element? Label maybe?

I ran into a similar issue early on. Seems HTML isn't allowed within the form builder.

**Comment by keoflex** [comment]
Yes i injected html wonder if ansi works

**Comment by thewizster** [comment]
#12 will handle this
