### ISSUE TITLE
Bug on Form Creation

### ISSUE THREAD

**Issue by keoflex** [thewizster/workorders#7]
When creating a form, the system will not let you save unless you have a district level approver.  Some forms only have group level approvers.  I think this is an easy fix but I am not sure where in the pageformsbuild.php to adjust this.

**Comment by thewizster** [comment]
Confirmed. This has roots in the earlier version before group approvers were added. I'll get this fixed.

**Comment by thewizster** [comment]
This issue is resolved in 91b301e
